# https://quarto-tdg.org/yaml.html
project:
  type: website
  output-dir: docs
  render:
    - src/plan.qmd
    - src/colors.ipynb

website:
  sidebar:
    style: "docked"
    contents:
      - section: "Intro"
        contents:
          - href: src/plan.qmd
            text: Statistical Analysis Plan
      - section: "Results"
        contents:
        - href: src/colors.ipynb
          text: Colors
  navbar:
    search: true
    left:
      - href: src/plan.qmd
        text: Statistical Analysis Plan
      - href: src/colors.ipynb
        text: Results

format:
  html:
    embed-resources: true
    theme:
      dark: darkly
      light: flatly
    fontsize: 1.1em
    css: styles.css
    toc: true
    execute:
    echo: false



